repository: "https://github.com/CornellCSWiki/CornellCSWiki"
repository_issues: "https://github.com/CornellCSWiki/CornellCSWiki/issues"
license: "https://github.com/CornellCSWiki/CornellCSWiki/blob/gh-pages/LICENSE"
moderators_email: "dml339@cornell.edu"
