repository: "https://github.com/CornellCSWiki/CornellCSWiki"
repository_issues: "https://github.com/CornellCSWiki/CornellCSWiki/issues"
license: "https://github.com/CornellCSWiki/CornellCSWiki/blob/master/LICENSE"
moderators_email: "ra534@cornell.edu"
